// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: valka/v1/api.proto

package valkav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- CreateTask ---
type CreateTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueueName      string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	TaskName       string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Input          string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"` // JSON string
	Priority       int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Metadata       string                 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`                          // JSON string
	ScheduledAt    string                 `protobuf:"bytes,9,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"` // RFC3339, empty = immediate
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_valka_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *CreateTaskRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTaskRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CreateTaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CreateTaskRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateTaskRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *CreateTaskRequest) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskMeta              `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_valka_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetTask() *TaskMeta {
	if x != nil {
		return x.Task
	}
	return nil
}

// --- GetTask ---
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_valka_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskMeta              `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_valka_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetTask() *TaskMeta {
	if x != nil {
		return x.Task
	}
	return nil
}

// --- ListTasks ---
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`    // optional filter
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=valka.v1.TaskStatus" json:"status,omitempty"` // optional filter
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_valka_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskMeta            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_valka_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksResponse) GetTasks() []*TaskMeta {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// --- CancelTask ---
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_valka_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskMeta              `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_valka_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTaskResponse) GetTask() *TaskMeta {
	if x != nil {
		return x.Task
	}
	return nil
}

// --- SubscribeLogs ---
type SubscribeLogsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskRunId      string                 `protobuf:"bytes,1,opt,name=task_run_id,json=taskRunId,proto3" json:"task_run_id,omitempty"`
	IncludeHistory bool                   `protobuf:"varint,2,opt,name=include_history,json=includeHistory,proto3" json:"include_history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeLogsRequest) Reset() {
	*x = SubscribeLogsRequest{}
	mi := &file_valka_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeLogsRequest) ProtoMessage() {}

func (x *SubscribeLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeLogsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeLogsRequest) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeLogsRequest) GetTaskRunId() string {
	if x != nil {
		return x.TaskRunId
	}
	return ""
}

func (x *SubscribeLogsRequest) GetIncludeHistory() bool {
	if x != nil {
		return x.IncludeHistory
	}
	return false
}

// --- SubscribeEvents ---
type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_valka_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_valka_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeEventsRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

var File_valka_v1_api_proto protoreflect.FileDescriptor

const file_valka_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x12valka/v1/api.proto\x12\bvalka.v1\x1a\x15valka/v1/common.proto\x1a\x15valka/v1/events.proto\x1a\x15valka/v1/worker.proto\"\xb3\x02\n" +
	"\x11CreateTaskRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\bmetadata\x18\b \x01(\tR\bmetadata\x12!\n" +
	"\fscheduled_at\x18\t \x01(\tR\vscheduledAt\"<\n" +
	"\x12CreateTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.valka.v1.TaskMetaR\x04task\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"9\n" +
	"\x0fGetTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.valka.v1.TaskMetaR\x04task\"\x95\x01\n" +
	"\x10ListTasksRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.valka.v1.TaskStatusR\x06status\x124\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x14.valka.v1.PaginationR\n" +
	"pagination\"e\n" +
	"\x11ListTasksResponse\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.valka.v1.TaskMetaR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"<\n" +
	"\x12CancelTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.valka.v1.TaskMetaR\x04task\"_\n" +
	"\x14SubscribeLogsRequest\x12\x1e\n" +
	"\vtask_run_id\x18\x01 \x01(\tR\ttaskRunId\x12'\n" +
	"\x0finclude_history\x18\x02 \x01(\bR\x0eincludeHistory\"7\n" +
	"\x16SubscribeEventsRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName2\xb7\x03\n" +
	"\n" +
	"ApiService\x12G\n" +
	"\n" +
	"CreateTask\x12\x1b.valka.v1.CreateTaskRequest\x1a\x1c.valka.v1.CreateTaskResponse\x12>\n" +
	"\aGetTask\x12\x18.valka.v1.GetTaskRequest\x1a\x19.valka.v1.GetTaskResponse\x12D\n" +
	"\tListTasks\x12\x1a.valka.v1.ListTasksRequest\x1a\x1b.valka.v1.ListTasksResponse\x12G\n" +
	"\n" +
	"CancelTask\x12\x1b.valka.v1.CancelTaskRequest\x1a\x1c.valka.v1.CancelTaskResponse\x12J\n" +
	"\x0fSubscribeEvents\x12 .valka.v1.SubscribeEventsRequest\x1a\x13.valka.v1.TaskEvent0\x01\x12E\n" +
	"\rSubscribeLogs\x12\x1e.valka.v1.SubscribeLogsRequest\x1a\x12.valka.v1.LogEntry0\x01b\x06proto3"

var (
	file_valka_v1_api_proto_rawDescOnce sync.Once
	file_valka_v1_api_proto_rawDescData []byte
)

func file_valka_v1_api_proto_rawDescGZIP() []byte {
	file_valka_v1_api_proto_rawDescOnce.Do(func() {
		file_valka_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_valka_v1_api_proto_rawDesc), len(file_valka_v1_api_proto_rawDesc)))
	})
	return file_valka_v1_api_proto_rawDescData
}

var file_valka_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_valka_v1_api_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),      // 0: valka.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),     // 1: valka.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),         // 2: valka.v1.GetTaskRequest
	(*GetTaskResponse)(nil),        // 3: valka.v1.GetTaskResponse
	(*ListTasksRequest)(nil),       // 4: valka.v1.ListTasksRequest
	(*ListTasksResponse)(nil),      // 5: valka.v1.ListTasksResponse
	(*CancelTaskRequest)(nil),      // 6: valka.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),     // 7: valka.v1.CancelTaskResponse
	(*SubscribeLogsRequest)(nil),   // 8: valka.v1.SubscribeLogsRequest
	(*SubscribeEventsRequest)(nil), // 9: valka.v1.SubscribeEventsRequest
	(*TaskMeta)(nil),               // 10: valka.v1.TaskMeta
	(TaskStatus)(0),                // 11: valka.v1.TaskStatus
	(*Pagination)(nil),             // 12: valka.v1.Pagination
	(*TaskEvent)(nil),              // 13: valka.v1.TaskEvent
	(*LogEntry)(nil),               // 14: valka.v1.LogEntry
}
var file_valka_v1_api_proto_depIdxs = []int32{
	10, // 0: valka.v1.CreateTaskResponse.task:type_name -> valka.v1.TaskMeta
	10, // 1: valka.v1.GetTaskResponse.task:type_name -> valka.v1.TaskMeta
	11, // 2: valka.v1.ListTasksRequest.status:type_name -> valka.v1.TaskStatus
	12, // 3: valka.v1.ListTasksRequest.pagination:type_name -> valka.v1.Pagination
	10, // 4: valka.v1.ListTasksResponse.tasks:type_name -> valka.v1.TaskMeta
	10, // 5: valka.v1.CancelTaskResponse.task:type_name -> valka.v1.TaskMeta
	0,  // 6: valka.v1.ApiService.CreateTask:input_type -> valka.v1.CreateTaskRequest
	2,  // 7: valka.v1.ApiService.GetTask:input_type -> valka.v1.GetTaskRequest
	4,  // 8: valka.v1.ApiService.ListTasks:input_type -> valka.v1.ListTasksRequest
	6,  // 9: valka.v1.ApiService.CancelTask:input_type -> valka.v1.CancelTaskRequest
	9,  // 10: valka.v1.ApiService.SubscribeEvents:input_type -> valka.v1.SubscribeEventsRequest
	8,  // 11: valka.v1.ApiService.SubscribeLogs:input_type -> valka.v1.SubscribeLogsRequest
	1,  // 12: valka.v1.ApiService.CreateTask:output_type -> valka.v1.CreateTaskResponse
	3,  // 13: valka.v1.ApiService.GetTask:output_type -> valka.v1.GetTaskResponse
	5,  // 14: valka.v1.ApiService.ListTasks:output_type -> valka.v1.ListTasksResponse
	7,  // 15: valka.v1.ApiService.CancelTask:output_type -> valka.v1.CancelTaskResponse
	13, // 16: valka.v1.ApiService.SubscribeEvents:output_type -> valka.v1.TaskEvent
	14, // 17: valka.v1.ApiService.SubscribeLogs:output_type -> valka.v1.LogEntry
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_valka_v1_api_proto_init() }
func file_valka_v1_api_proto_init() {
	if File_valka_v1_api_proto != nil {
		return
	}
	file_valka_v1_common_proto_init()
	file_valka_v1_events_proto_init()
	file_valka_v1_worker_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valka_v1_api_proto_rawDesc), len(file_valka_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_valka_v1_api_proto_goTypes,
		DependencyIndexes: file_valka_v1_api_proto_depIdxs,
		MessageInfos:      file_valka_v1_api_proto_msgTypes,
	}.Build()
	File_valka_v1_api_proto = out.File
	file_valka_v1_api_proto_goTypes = nil
	file_valka_v1_api_proto_depIdxs = nil
}
