// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: valka/v1/common.proto

package valkav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_DISPATCHING TaskStatus = 2
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 3
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 4
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 5
	TaskStatus_TASK_STATUS_RETRY       TaskStatus = 6
	TaskStatus_TASK_STATUS_DEAD_LETTER TaskStatus = 7
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 8
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_DISPATCHING",
		3: "TASK_STATUS_RUNNING",
		4: "TASK_STATUS_COMPLETED",
		5: "TASK_STATUS_FAILED",
		6: "TASK_STATUS_RETRY",
		7: "TASK_STATUS_DEAD_LETTER",
		8: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_DISPATCHING": 2,
		"TASK_STATUS_RUNNING":     3,
		"TASK_STATUS_COMPLETED":   4,
		"TASK_STATUS_FAILED":      5,
		"TASK_STATUS_RETRY":       6,
		"TASK_STATUS_DEAD_LETTER": 7,
		"TASK_STATUS_CANCELLED":   8,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_valka_v1_common_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_valka_v1_common_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_valka_v1_common_proto_rawDescGZIP(), []int{0}
}

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_valka_v1_common_proto_enumTypes[1].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_valka_v1_common_proto_enumTypes[1]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_valka_v1_common_proto_rawDescGZIP(), []int{1}
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_valka_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_valka_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type TaskMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QueueName      string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	TaskName       string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Status         TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=valka.v1.TaskStatus" json:"status,omitempty"`
	Priority       int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	AttemptCount   int32                  `protobuf:"varint,7,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Input          string                 `protobuf:"bytes,10,opt,name=input,proto3" json:"input,omitempty"`       // JSON string
	Metadata       string                 `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON string
	Output         string                 `protobuf:"bytes,12,opt,name=output,proto3" json:"output,omitempty"`     // JSON string (from completed run)
	ErrorMessage   string                 `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ScheduledAt    string                 `protobuf:"bytes,14,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"` // RFC3339
	CreatedAt      string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`       // RFC3339
	UpdatedAt      string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`       // RFC3339
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskMeta) Reset() {
	*x = TaskMeta{}
	mi := &file_valka_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMeta) ProtoMessage() {}

func (x *TaskMeta) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMeta.ProtoReflect.Descriptor instead.
func (*TaskMeta) Descriptor() ([]byte, []int) {
	return file_valka_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *TaskMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskMeta) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *TaskMeta) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskMeta) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskMeta) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskMeta) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *TaskMeta) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *TaskMeta) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskMeta) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TaskMeta) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TaskMeta) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *TaskMeta) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskMeta) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskMeta) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

func (x *TaskMeta) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TaskMeta) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_valka_v1_common_proto protoreflect.FileDescriptor

const file_valka_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15valka/v1/common.proto\x12\bvalka.v1\"H\n" +
	"\n" +
	"Pagination\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x88\x04\n" +
	"\bTaskMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.valka.v1.TaskStatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x06 \x01(\x05R\n" +
	"maxRetries\x12#\n" +
	"\rattempt_count\x18\a \x01(\x05R\fattemptCount\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\x12\x14\n" +
	"\x05input\x18\n" +
	" \x01(\tR\x05input\x12\x1a\n" +
	"\bmetadata\x18\v \x01(\tR\bmetadata\x12\x16\n" +
	"\x06output\x18\f \x01(\tR\x06output\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x12!\n" +
	"\fscheduled_at\x18\x0e \x01(\tR\vscheduledAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt*\xfa\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_DISPATCHING\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x05\x12\x15\n" +
	"\x11TASK_STATUS_RETRY\x10\x06\x12\x1b\n" +
	"\x17TASK_STATUS_DEAD_LETTER\x10\a\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\b*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04b\x06proto3"

var (
	file_valka_v1_common_proto_rawDescOnce sync.Once
	file_valka_v1_common_proto_rawDescData []byte
)

func file_valka_v1_common_proto_rawDescGZIP() []byte {
	file_valka_v1_common_proto_rawDescOnce.Do(func() {
		file_valka_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_valka_v1_common_proto_rawDesc), len(file_valka_v1_common_proto_rawDesc)))
	})
	return file_valka_v1_common_proto_rawDescData
}

var file_valka_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_valka_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_valka_v1_common_proto_goTypes = []any{
	(TaskStatus)(0),    // 0: valka.v1.TaskStatus
	(LogLevel)(0),      // 1: valka.v1.LogLevel
	(*Pagination)(nil), // 2: valka.v1.Pagination
	(*TaskMeta)(nil),   // 3: valka.v1.TaskMeta
}
var file_valka_v1_common_proto_depIdxs = []int32{
	0, // 0: valka.v1.TaskMeta.status:type_name -> valka.v1.TaskStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_valka_v1_common_proto_init() }
func file_valka_v1_common_proto_init() {
	if File_valka_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valka_v1_common_proto_rawDesc), len(file_valka_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_valka_v1_common_proto_goTypes,
		DependencyIndexes: file_valka_v1_common_proto_depIdxs,
		EnumInfos:         file_valka_v1_common_proto_enumTypes,
		MessageInfos:      file_valka_v1_common_proto_msgTypes,
	}.Build()
	File_valka_v1_common_proto = out.File
	file_valka_v1_common_proto_goTypes = nil
	file_valka_v1_common_proto_depIdxs = nil
}
