// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: valka/v1/events.proto

package valkav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	QueueName      string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	PreviousStatus TaskStatus             `protobuf:"varint,4,opt,name=previous_status,json=previousStatus,proto3,enum=valka.v1.TaskStatus" json:"previous_status,omitempty"`
	NewStatus      TaskStatus             `protobuf:"varint,5,opt,name=new_status,json=newStatus,proto3,enum=valka.v1.TaskStatus" json:"new_status,omitempty"`
	WorkerId       string                 `protobuf:"bytes,6,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AttemptNumber  int32                  `protobuf:"varint,8,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TimestampMs    int64                  `protobuf:"varint,10,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_valka_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_valka_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *TaskEvent) GetPreviousStatus() TaskStatus {
	if x != nil {
		return x.PreviousStatus
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskEvent) GetNewStatus() TaskStatus {
	if x != nil {
		return x.NewStatus
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskEvent) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskEvent) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *TaskEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_valka_v1_events_proto protoreflect.FileDescriptor

const file_valka_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x15valka/v1/events.proto\x12\bvalka.v1\x1a\x15valka/v1/common.proto\"\xf7\x02\n" +
	"\tTaskEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12=\n" +
	"\x0fprevious_status\x18\x04 \x01(\x0e2\x14.valka.v1.TaskStatusR\x0epreviousStatus\x123\n" +
	"\n" +
	"new_status\x18\x05 \x01(\x0e2\x14.valka.v1.TaskStatusR\tnewStatus\x12\x1b\n" +
	"\tworker_id\x18\x06 \x01(\tR\bworkerId\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12%\n" +
	"\x0eattempt_number\x18\b \x01(\x05R\rattemptNumber\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12!\n" +
	"\ftimestamp_ms\x18\n" +
	" \x01(\x03R\vtimestampMsb\x06proto3"

var (
	file_valka_v1_events_proto_rawDescOnce sync.Once
	file_valka_v1_events_proto_rawDescData []byte
)

func file_valka_v1_events_proto_rawDescGZIP() []byte {
	file_valka_v1_events_proto_rawDescOnce.Do(func() {
		file_valka_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_valka_v1_events_proto_rawDesc), len(file_valka_v1_events_proto_rawDesc)))
	})
	return file_valka_v1_events_proto_rawDescData
}

var file_valka_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_valka_v1_events_proto_goTypes = []any{
	(*TaskEvent)(nil), // 0: valka.v1.TaskEvent
	(TaskStatus)(0),   // 1: valka.v1.TaskStatus
}
var file_valka_v1_events_proto_depIdxs = []int32{
	1, // 0: valka.v1.TaskEvent.previous_status:type_name -> valka.v1.TaskStatus
	1, // 1: valka.v1.TaskEvent.new_status:type_name -> valka.v1.TaskStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_valka_v1_events_proto_init() }
func file_valka_v1_events_proto_init() {
	if File_valka_v1_events_proto != nil {
		return
	}
	file_valka_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valka_v1_events_proto_rawDesc), len(file_valka_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_valka_v1_events_proto_goTypes,
		DependencyIndexes: file_valka_v1_events_proto_depIdxs,
		MessageInfos:      file_valka_v1_events_proto_msgTypes,
	}.Build()
	File_valka_v1_events_proto = out.File
	file_valka_v1_events_proto_goTypes = nil
	file_valka_v1_events_proto_depIdxs = nil
}
