// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: valka/v1/worker.proto

package valkav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Worker -> Server
type WorkerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*WorkerRequest_Hello
	//	*WorkerRequest_TaskResult
	//	*WorkerRequest_Heartbeat
	//	*WorkerRequest_LogBatch
	//	*WorkerRequest_Shutdown
	//	*WorkerRequest_SignalAck
	Request       isWorkerRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRequest) Reset() {
	*x = WorkerRequest{}
	mi := &file_valka_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRequest) ProtoMessage() {}

func (x *WorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRequest.ProtoReflect.Descriptor instead.
func (*WorkerRequest) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRequest) GetRequest() isWorkerRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *WorkerRequest) GetHello() *WorkerHello {
	if x != nil {
		if x, ok := x.Request.(*WorkerRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerRequest) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Request.(*WorkerRequest_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *WorkerRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Request.(*WorkerRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerRequest) GetLogBatch() *LogBatch {
	if x != nil {
		if x, ok := x.Request.(*WorkerRequest_LogBatch); ok {
			return x.LogBatch
		}
	}
	return nil
}

func (x *WorkerRequest) GetShutdown() *GracefulShutdown {
	if x != nil {
		if x, ok := x.Request.(*WorkerRequest_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *WorkerRequest) GetSignalAck() *SignalAck {
	if x != nil {
		if x, ok := x.Request.(*WorkerRequest_SignalAck); ok {
			return x.SignalAck
		}
	}
	return nil
}

type isWorkerRequest_Request interface {
	isWorkerRequest_Request()
}

type WorkerRequest_Hello struct {
	Hello *WorkerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerRequest_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,2,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type WorkerRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type WorkerRequest_LogBatch struct {
	LogBatch *LogBatch `protobuf:"bytes,4,opt,name=log_batch,json=logBatch,proto3,oneof"`
}

type WorkerRequest_Shutdown struct {
	Shutdown *GracefulShutdown `protobuf:"bytes,5,opt,name=shutdown,proto3,oneof"`
}

type WorkerRequest_SignalAck struct {
	SignalAck *SignalAck `protobuf:"bytes,6,opt,name=signal_ack,json=signalAck,proto3,oneof"`
}

func (*WorkerRequest_Hello) isWorkerRequest_Request() {}

func (*WorkerRequest_TaskResult) isWorkerRequest_Request() {}

func (*WorkerRequest_Heartbeat) isWorkerRequest_Request() {}

func (*WorkerRequest_LogBatch) isWorkerRequest_Request() {}

func (*WorkerRequest_Shutdown) isWorkerRequest_Request() {}

func (*WorkerRequest_SignalAck) isWorkerRequest_Request() {}

// Server -> Worker
type WorkerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*WorkerResponse_TaskAssignment
	//	*WorkerResponse_TaskCancellation
	//	*WorkerResponse_HeartbeatAck
	//	*WorkerResponse_ServerShutdown
	//	*WorkerResponse_TaskSignal
	Response      isWorkerResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerResponse) Reset() {
	*x = WorkerResponse{}
	mi := &file_valka_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResponse) ProtoMessage() {}

func (x *WorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResponse.ProtoReflect.Descriptor instead.
func (*WorkerResponse) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerResponse) GetResponse() isWorkerResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *WorkerResponse) GetTaskAssignment() *TaskAssignment {
	if x != nil {
		if x, ok := x.Response.(*WorkerResponse_TaskAssignment); ok {
			return x.TaskAssignment
		}
	}
	return nil
}

func (x *WorkerResponse) GetTaskCancellation() *TaskCancellation {
	if x != nil {
		if x, ok := x.Response.(*WorkerResponse_TaskCancellation); ok {
			return x.TaskCancellation
		}
	}
	return nil
}

func (x *WorkerResponse) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Response.(*WorkerResponse_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *WorkerResponse) GetServerShutdown() *ServerShutdown {
	if x != nil {
		if x, ok := x.Response.(*WorkerResponse_ServerShutdown); ok {
			return x.ServerShutdown
		}
	}
	return nil
}

func (x *WorkerResponse) GetTaskSignal() *TaskSignal {
	if x != nil {
		if x, ok := x.Response.(*WorkerResponse_TaskSignal); ok {
			return x.TaskSignal
		}
	}
	return nil
}

type isWorkerResponse_Response interface {
	isWorkerResponse_Response()
}

type WorkerResponse_TaskAssignment struct {
	TaskAssignment *TaskAssignment `protobuf:"bytes,1,opt,name=task_assignment,json=taskAssignment,proto3,oneof"`
}

type WorkerResponse_TaskCancellation struct {
	TaskCancellation *TaskCancellation `protobuf:"bytes,2,opt,name=task_cancellation,json=taskCancellation,proto3,oneof"`
}

type WorkerResponse_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,3,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type WorkerResponse_ServerShutdown struct {
	ServerShutdown *ServerShutdown `protobuf:"bytes,4,opt,name=server_shutdown,json=serverShutdown,proto3,oneof"`
}

type WorkerResponse_TaskSignal struct {
	TaskSignal *TaskSignal `protobuf:"bytes,5,opt,name=task_signal,json=taskSignal,proto3,oneof"`
}

func (*WorkerResponse_TaskAssignment) isWorkerResponse_Response() {}

func (*WorkerResponse_TaskCancellation) isWorkerResponse_Response() {}

func (*WorkerResponse_HeartbeatAck) isWorkerResponse_Response() {}

func (*WorkerResponse_ServerShutdown) isWorkerResponse_Response() {}

func (*WorkerResponse_TaskSignal) isWorkerResponse_Response() {}

type WorkerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerName    string                 `protobuf:"bytes,2,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Queues        []string               `protobuf:"bytes,3,rep,name=queues,proto3" json:"queues,omitempty"`
	Concurrency   int32                  `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHello) Reset() {
	*x = WorkerHello{}
	mi := &file_valka_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHello) ProtoMessage() {}

func (x *WorkerHello) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHello.ProtoReflect.Descriptor instead.
func (*WorkerHello) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerHello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHello) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *WorkerHello) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *WorkerHello) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *WorkerHello) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskRunId     string                 `protobuf:"bytes,2,opt,name=task_run_id,json=taskRunId,proto3" json:"task_run_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"` // JSON string
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_valka_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetTaskRunId() string {
	if x != nil {
		return x.TaskRunId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveTaskIds []string               `protobuf:"bytes,1,rep,name=active_task_ids,json=activeTaskIds,proto3" json:"active_task_ids,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_valka_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetActiveTaskIds() []string {
	if x != nil {
		return x.ActiveTaskIds
	}
	return nil
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_valka_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskRunId     string                 `protobuf:"bytes,1,opt,name=task_run_id,json=taskRunId,proto3" json:"task_run_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Level         LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=valka.v1.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_valka_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *LogEntry) GetTaskRunId() string {
	if x != nil {
		return x.TaskRunId
	}
	return ""
}

func (x *LogEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type GracefulShutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GracefulShutdown) Reset() {
	*x = GracefulShutdown{}
	mi := &file_valka_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GracefulShutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GracefulShutdown) ProtoMessage() {}

func (x *GracefulShutdown) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GracefulShutdown.ProtoReflect.Descriptor instead.
func (*GracefulShutdown) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *GracefulShutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TaskAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskRunId      string                 `protobuf:"bytes,2,opt,name=task_run_id,json=taskRunId,proto3" json:"task_run_id,omitempty"`
	QueueName      string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	TaskName       string                 `protobuf:"bytes,4,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Input          string                 `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"` // JSON string
	AttemptNumber  int32                  `protobuf:"varint,6,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Metadata       string                 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON string
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_valka_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetTaskRunId() string {
	if x != nil {
		return x.TaskRunId
	}
	return ""
}

func (x *TaskAssignment) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *TaskAssignment) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskAssignment) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TaskAssignment) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *TaskAssignment) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskAssignment) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type TaskCancellation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCancellation) Reset() {
	*x = TaskCancellation{}
	mi := &file_valka_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCancellation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCancellation) ProtoMessage() {}

func (x *TaskCancellation) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCancellation.ProtoReflect.Descriptor instead.
func (*TaskCancellation) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *TaskCancellation) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCancellation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HeartbeatAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerTimestampMs int64                  `protobuf:"varint,1,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_valka_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatAck) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

type ServerShutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	DrainSeconds  int32                  `protobuf:"varint,2,opt,name=drain_seconds,json=drainSeconds,proto3" json:"drain_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerShutdown) Reset() {
	*x = ServerShutdown{}
	mi := &file_valka_v1_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerShutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerShutdown) ProtoMessage() {}

func (x *ServerShutdown) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerShutdown.ProtoReflect.Descriptor instead.
func (*ServerShutdown) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{11}
}

func (x *ServerShutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ServerShutdown) GetDrainSeconds() int32 {
	if x != nil {
		return x.DrainSeconds
	}
	return 0
}

type TaskSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SignalName    string                 `protobuf:"bytes,3,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // JSON string
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSignal) Reset() {
	*x = TaskSignal{}
	mi := &file_valka_v1_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSignal) ProtoMessage() {}

func (x *TaskSignal) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSignal.ProtoReflect.Descriptor instead.
func (*TaskSignal) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{12}
}

func (x *TaskSignal) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *TaskSignal) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskSignal) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *TaskSignal) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *TaskSignal) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type SignalAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalAck) Reset() {
	*x = SignalAck{}
	mi := &file_valka_v1_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalAck) ProtoMessage() {}

func (x *SignalAck) ProtoReflect() protoreflect.Message {
	mi := &file_valka_v1_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalAck.ProtoReflect.Descriptor instead.
func (*SignalAck) Descriptor() ([]byte, []int) {
	return file_valka_v1_worker_proto_rawDescGZIP(), []int{13}
}

func (x *SignalAck) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

var File_valka_v1_worker_proto protoreflect.FileDescriptor

const file_valka_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x15valka/v1/worker.proto\x12\bvalka.v1\x1a\x15valka/v1/common.proto\"\xda\x02\n" +
	"\rWorkerRequest\x12-\n" +
	"\x05hello\x18\x01 \x01(\v2\x15.valka.v1.WorkerHelloH\x00R\x05hello\x127\n" +
	"\vtask_result\x18\x02 \x01(\v2\x14.valka.v1.TaskResultH\x00R\n" +
	"taskResult\x123\n" +
	"\theartbeat\x18\x03 \x01(\v2\x13.valka.v1.HeartbeatH\x00R\theartbeat\x121\n" +
	"\tlog_batch\x18\x04 \x01(\v2\x12.valka.v1.LogBatchH\x00R\blogBatch\x128\n" +
	"\bshutdown\x18\x05 \x01(\v2\x1a.valka.v1.GracefulShutdownH\x00R\bshutdown\x124\n" +
	"\n" +
	"signal_ack\x18\x06 \x01(\v2\x13.valka.v1.SignalAckH\x00R\tsignalAckB\t\n" +
	"\arequest\"\xe9\x02\n" +
	"\x0eWorkerResponse\x12C\n" +
	"\x0ftask_assignment\x18\x01 \x01(\v2\x18.valka.v1.TaskAssignmentH\x00R\x0etaskAssignment\x12I\n" +
	"\x11task_cancellation\x18\x02 \x01(\v2\x1a.valka.v1.TaskCancellationH\x00R\x10taskCancellation\x12=\n" +
	"\rheartbeat_ack\x18\x03 \x01(\v2\x16.valka.v1.HeartbeatAckH\x00R\fheartbeatAck\x12C\n" +
	"\x0fserver_shutdown\x18\x04 \x01(\v2\x18.valka.v1.ServerShutdownH\x00R\x0eserverShutdown\x127\n" +
	"\vtask_signal\x18\x05 \x01(\v2\x14.valka.v1.TaskSignalH\x00R\n" +
	"taskSignalB\n" +
	"\n" +
	"\bresponse\"\xa1\x01\n" +
	"\vWorkerHello\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vworker_name\x18\x02 \x01(\tR\n" +
	"workerName\x12\x16\n" +
	"\x06queues\x18\x03 \x03(\tR\x06queues\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x05R\vconcurrency\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"\xba\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1e\n" +
	"\vtask_run_id\x18\x02 \x01(\tR\ttaskRunId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"V\n" +
	"\tHeartbeat\x12&\n" +
	"\x0factive_task_ids\x18\x01 \x03(\tR\ractiveTaskIds\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"8\n" +
	"\bLogBatch\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.valka.v1.LogEntryR\aentries\"\xad\x01\n" +
	"\bLogEntry\x12\x1e\n" +
	"\vtask_run_id\x18\x01 \x01(\tR\ttaskRunId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12(\n" +
	"\x05level\x18\x03 \x01(\x0e2\x12.valka.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"*\n" +
	"\x10GracefulShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x87\x02\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1e\n" +
	"\vtask_run_id\x18\x02 \x01(\tR\ttaskRunId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12\x1b\n" +
	"\ttask_name\x18\x04 \x01(\tR\btaskName\x12\x14\n" +
	"\x05input\x18\x05 \x01(\tR\x05input\x12%\n" +
	"\x0eattempt_number\x18\x06 \x01(\x05R\rattemptNumber\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x12\x1a\n" +
	"\bmetadata\x18\b \x01(\tR\bmetadata\"C\n" +
	"\x10TaskCancellation\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\">\n" +
	"\fHeartbeatAck\x12.\n" +
	"\x13server_timestamp_ms\x18\x01 \x01(\x03R\x11serverTimestampMs\"M\n" +
	"\x0eServerShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12#\n" +
	"\rdrain_seconds\x18\x02 \x01(\x05R\fdrainSeconds\"\xa0\x01\n" +
	"\n" +
	"TaskSignal\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vsignal_name\x18\x03 \x01(\tR\n" +
	"signalName\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"(\n" +
	"\tSignalAck\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId2Q\n" +
	"\rWorkerService\x12@\n" +
	"\aSession\x12\x17.valka.v1.WorkerRequest\x1a\x18.valka.v1.WorkerResponse(\x010\x01b\x06proto3"

var (
	file_valka_v1_worker_proto_rawDescOnce sync.Once
	file_valka_v1_worker_proto_rawDescData []byte
)

func file_valka_v1_worker_proto_rawDescGZIP() []byte {
	file_valka_v1_worker_proto_rawDescOnce.Do(func() {
		file_valka_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_valka_v1_worker_proto_rawDesc), len(file_valka_v1_worker_proto_rawDesc)))
	})
	return file_valka_v1_worker_proto_rawDescData
}

var file_valka_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_valka_v1_worker_proto_goTypes = []any{
	(*WorkerRequest)(nil),    // 0: valka.v1.WorkerRequest
	(*WorkerResponse)(nil),   // 1: valka.v1.WorkerResponse
	(*WorkerHello)(nil),      // 2: valka.v1.WorkerHello
	(*TaskResult)(nil),       // 3: valka.v1.TaskResult
	(*Heartbeat)(nil),        // 4: valka.v1.Heartbeat
	(*LogBatch)(nil),         // 5: valka.v1.LogBatch
	(*LogEntry)(nil),         // 6: valka.v1.LogEntry
	(*GracefulShutdown)(nil), // 7: valka.v1.GracefulShutdown
	(*TaskAssignment)(nil),   // 8: valka.v1.TaskAssignment
	(*TaskCancellation)(nil), // 9: valka.v1.TaskCancellation
	(*HeartbeatAck)(nil),     // 10: valka.v1.HeartbeatAck
	(*ServerShutdown)(nil),   // 11: valka.v1.ServerShutdown
	(*TaskSignal)(nil),       // 12: valka.v1.TaskSignal
	(*SignalAck)(nil),        // 13: valka.v1.SignalAck
	(LogLevel)(0),            // 14: valka.v1.LogLevel
}
var file_valka_v1_worker_proto_depIdxs = []int32{
	2,  // 0: valka.v1.WorkerRequest.hello:type_name -> valka.v1.WorkerHello
	3,  // 1: valka.v1.WorkerRequest.task_result:type_name -> valka.v1.TaskResult
	4,  // 2: valka.v1.WorkerRequest.heartbeat:type_name -> valka.v1.Heartbeat
	5,  // 3: valka.v1.WorkerRequest.log_batch:type_name -> valka.v1.LogBatch
	7,  // 4: valka.v1.WorkerRequest.shutdown:type_name -> valka.v1.GracefulShutdown
	13, // 5: valka.v1.WorkerRequest.signal_ack:type_name -> valka.v1.SignalAck
	8,  // 6: valka.v1.WorkerResponse.task_assignment:type_name -> valka.v1.TaskAssignment
	9,  // 7: valka.v1.WorkerResponse.task_cancellation:type_name -> valka.v1.TaskCancellation
	10, // 8: valka.v1.WorkerResponse.heartbeat_ack:type_name -> valka.v1.HeartbeatAck
	11, // 9: valka.v1.WorkerResponse.server_shutdown:type_name -> valka.v1.ServerShutdown
	12, // 10: valka.v1.WorkerResponse.task_signal:type_name -> valka.v1.TaskSignal
	6,  // 11: valka.v1.LogBatch.entries:type_name -> valka.v1.LogEntry
	14, // 12: valka.v1.LogEntry.level:type_name -> valka.v1.LogLevel
	0,  // 13: valka.v1.WorkerService.Session:input_type -> valka.v1.WorkerRequest
	1,  // 14: valka.v1.WorkerService.Session:output_type -> valka.v1.WorkerResponse
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_valka_v1_worker_proto_init() }
func file_valka_v1_worker_proto_init() {
	if File_valka_v1_worker_proto != nil {
		return
	}
	file_valka_v1_common_proto_init()
	file_valka_v1_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerRequest_Hello)(nil),
		(*WorkerRequest_TaskResult)(nil),
		(*WorkerRequest_Heartbeat)(nil),
		(*WorkerRequest_LogBatch)(nil),
		(*WorkerRequest_Shutdown)(nil),
		(*WorkerRequest_SignalAck)(nil),
	}
	file_valka_v1_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*WorkerResponse_TaskAssignment)(nil),
		(*WorkerResponse_TaskCancellation)(nil),
		(*WorkerResponse_HeartbeatAck)(nil),
		(*WorkerResponse_ServerShutdown)(nil),
		(*WorkerResponse_TaskSignal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valka_v1_worker_proto_rawDesc), len(file_valka_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_valka_v1_worker_proto_goTypes,
		DependencyIndexes: file_valka_v1_worker_proto_depIdxs,
		MessageInfos:      file_valka_v1_worker_proto_msgTypes,
	}.Build()
	File_valka_v1_worker_proto = out.File
	file_valka_v1_worker_proto_goTypes = nil
	file_valka_v1_worker_proto_depIdxs = nil
}
