# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import api_pb2 as valka_dot_v1_dot_api__pb2
from . import events_pb2 as valka_dot_v1_dot_events__pb2
from . import worker_pb2 as valka_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in valka/v1/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/valka.v1.ApiService/CreateTask',
                request_serializer=valka_dot_v1_dot_api__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=valka_dot_v1_dot_api__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/valka.v1.ApiService/GetTask',
                request_serializer=valka_dot_v1_dot_api__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=valka_dot_v1_dot_api__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/valka.v1.ApiService/ListTasks',
                request_serializer=valka_dot_v1_dot_api__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=valka_dot_v1_dot_api__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/valka.v1.ApiService/CancelTask',
                request_serializer=valka_dot_v1_dot_api__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=valka_dot_v1_dot_api__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/valka.v1.ApiService/SubscribeEvents',
                request_serializer=valka_dot_v1_dot_api__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=valka_dot_v1_dot_events__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.SubscribeLogs = channel.unary_stream(
                '/valka.v1.ApiService/SubscribeLogs',
                request_serializer=valka_dot_v1_dot_api__pb2.SubscribeLogsRequest.SerializeToString,
                response_deserializer=valka_dot_v1_dot_worker__pb2.LogEntry.FromString,
                _registered_method=True)


class ApiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Task CRUD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Event streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeLogs(self, request, context):
        """Log streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=valka_dot_v1_dot_api__pb2.CreateTaskRequest.FromString,
                    response_serializer=valka_dot_v1_dot_api__pb2.CreateTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=valka_dot_v1_dot_api__pb2.GetTaskRequest.FromString,
                    response_serializer=valka_dot_v1_dot_api__pb2.GetTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=valka_dot_v1_dot_api__pb2.ListTasksRequest.FromString,
                    response_serializer=valka_dot_v1_dot_api__pb2.ListTasksResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=valka_dot_v1_dot_api__pb2.CancelTaskRequest.FromString,
                    response_serializer=valka_dot_v1_dot_api__pb2.CancelTaskResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=valka_dot_v1_dot_api__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=valka_dot_v1_dot_events__pb2.TaskEvent.SerializeToString,
            ),
            'SubscribeLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeLogs,
                    request_deserializer=valka_dot_v1_dot_api__pb2.SubscribeLogsRequest.FromString,
                    response_serializer=valka_dot_v1_dot_worker__pb2.LogEntry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'valka.v1.ApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('valka.v1.ApiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/valka.v1.ApiService/CreateTask',
            valka_dot_v1_dot_api__pb2.CreateTaskRequest.SerializeToString,
            valka_dot_v1_dot_api__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/valka.v1.ApiService/GetTask',
            valka_dot_v1_dot_api__pb2.GetTaskRequest.SerializeToString,
            valka_dot_v1_dot_api__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/valka.v1.ApiService/ListTasks',
            valka_dot_v1_dot_api__pb2.ListTasksRequest.SerializeToString,
            valka_dot_v1_dot_api__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/valka.v1.ApiService/CancelTask',
            valka_dot_v1_dot_api__pb2.CancelTaskRequest.SerializeToString,
            valka_dot_v1_dot_api__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/valka.v1.ApiService/SubscribeEvents',
            valka_dot_v1_dot_api__pb2.SubscribeEventsRequest.SerializeToString,
            valka_dot_v1_dot_events__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/valka.v1.ApiService/SubscribeLogs',
            valka_dot_v1_dot_api__pb2.SubscribeLogsRequest.SerializeToString,
            valka_dot_v1_dot_worker__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
