# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: valka/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'valka/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15valka/v1/common.proto\x12\x08valka.v1\"3\n\nPagination\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\"\xd9\x02\n\x08TaskMeta\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nqueue_name\x18\x02 \x01(\t\x12\x11\n\ttask_name\x18\x03 \x01(\t\x12$\n\x06status\x18\x04 \x01(\x0e\x32\x14.valka.v1.TaskStatus\x12\x10\n\x08priority\x18\x05 \x01(\x05\x12\x13\n\x0bmax_retries\x18\x06 \x01(\x05\x12\x15\n\rattempt_count\x18\x07 \x01(\x05\x12\x17\n\x0ftimeout_seconds\x18\x08 \x01(\x05\x12\x17\n\x0fidempotency_key\x18\t \x01(\t\x12\r\n\x05input\x18\n \x01(\t\x12\x10\n\x08metadata\x18\x0b \x01(\t\x12\x0e\n\x06output\x18\x0c \x01(\t\x12\x15\n\rerror_message\x18\r \x01(\t\x12\x14\n\x0cscheduled_at\x18\x0e \x01(\t\x12\x12\n\ncreated_at\x18\x0f \x01(\t\x12\x12\n\nupdated_at\x18\x10 \x01(\t*\xfa\x01\n\nTaskStatus\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13TASK_STATUS_PENDING\x10\x01\x12\x1b\n\x17TASK_STATUS_DISPATCHING\x10\x02\x12\x17\n\x13TASK_STATUS_RUNNING\x10\x03\x12\x19\n\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n\x12TASK_STATUS_FAILED\x10\x05\x12\x15\n\x11TASK_STATUS_RETRY\x10\x06\x12\x1b\n\x17TASK_STATUS_DEAD_LETTER\x10\x07\x12\x19\n\x15TASK_STATUS_CANCELLED\x10\x08*w\n\x08LogLevel\x12\x19\n\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n\x0fLOG_LEVEL_ERROR\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'valka.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKSTATUS']._serialized_start=437
  _globals['_TASKSTATUS']._serialized_end=687
  _globals['_LOGLEVEL']._serialized_start=689
  _globals['_LOGLEVEL']._serialized_end=808
  _globals['_PAGINATION']._serialized_start=35
  _globals['_PAGINATION']._serialized_end=86
  _globals['_TASKMETA']._serialized_start=89
  _globals['_TASKMETA']._serialized_end=434
# @@protoc_insertion_point(module_scope)
