# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: valka/v1/events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'valka/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as valka_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15valka/v1/events.proto\x12\x08valka.v1\x1a\x15valka/v1/common.proto\"\x84\x02\n\tTaskEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x12\n\nqueue_name\x18\x03 \x01(\t\x12-\n\x0fprevious_status\x18\x04 \x01(\x0e\x32\x14.valka.v1.TaskStatus\x12(\n\nnew_status\x18\x05 \x01(\x0e\x32\x14.valka.v1.TaskStatus\x12\x11\n\tworker_id\x18\x06 \x01(\t\x12\x0f\n\x07node_id\x18\x07 \x01(\t\x12\x16\n\x0e\x61ttempt_number\x18\x08 \x01(\x05\x12\x15\n\rerror_message\x18\t \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\n \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'valka.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKEVENT']._serialized_start=59
  _globals['_TASKEVENT']._serialized_end=319
# @@protoc_insertion_point(module_scope)
