{{- if and (not .Values.storage.existingSecret) (or .Values.storage.accessKeyId .Values.storage.secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valka.fullname" . }}-s3
  labels:
    {{- include "valka.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.storage.accessKeyId | quote }}
  secret-access-key: {{ .Values.storage.secretAccessKey | quote }}
{{- end }}
